// PCNT validation sketch (ESP32-S3) — direct register driver (no esp-idf PCNT
// driver). Routes GPIO4 into PCNT unit 0 channel 0 via the GPIO-matrix input
// (FUNC_IN_SEL_CFG), counts N rising edges generated by toggling the pin, and
// reads the result. Compiled with arduino-cli; runs identically on real silicon.
// Validates the emulator's PCNT edge-counter model + GPIO-matrix input routing.

#define PCNT_BASE 0x60086000UL
#define GPIO_BASE 0x60004000UL

volatile uint32_t* const PCNT = (volatile uint32_t* const)PCNT_BASE;
volatile uint32_t* const GPIO = (volatile uint32_t* const)GPIO_BASE;

// PCNT_SIG_CH0_IN0_IDX = 33. FUNC_IN_SEL_CFG[33] at GPIO 0x154 + 33*4.
#define FUNC_IN_SEL(sig) GPIO[((0x154 / 4) + (sig))]

void setup() {
  Serial.begin(115200);
  // Enable peripheral clocks (SYSCON gating: frozen otherwise).
  *(volatile uint32_t*)(0x600C0018) |= (1u << 10);
  delay(50);
  pinMode(4, OUTPUT);
  digitalWrite(4, LOW);

  // Route GPIO4 to PCNT unit0 channel0 signal (no invert).
  FUNC_IN_SEL(33) = 4;

  // Unit0 channel0: increment on positive edge, disable on negative edge.
  PCNT[0x00 / 4] = (1u << 18) | (0u << 16);  // CONF0
  PCNT[0x04 / 4] = 0;                         // CONF1
  PCNT[0x08 / 4] = 0x0000FFFF;               // CONF2: h_lim=0xFFFF, l_lim=0
  PCNT[0x60 / 4] = 0;                        // CTRL: clear reset + unpause

  const int N = 100;
  for (int i = 0; i < N; i++) {
    digitalWrite(4, HIGH);
    digitalWrite(4, LOW);
  }
  uint32_t count = PCNT[0x30 / 4] & 0xFFFF;
  Serial.print("PCNT count=");
  Serial.println(count);
  Serial.println(count == N ? "PCNT PASS" : "PCNT FAIL");
}

void loop() {}
